//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Loadingwnd_prefab
    {
        public const string BundleName = "loadingwnd_prefab";
        public const string LOADINGWND = "loadingwnd";
    }
    public class Loginwnd_prefab
    {
        public const string BundleName = "loginwnd_prefab";
        public const string LOGINWND = "loginwnd";
    }
    public class Scenelogin_unity
    {
        public const string BundleName = "scenelogin_unity";
        public const string SCENELOGIN = "scenelogin";
    }
}
