//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;


    public class LoadingWndData : QFramework.UIPanelData
    {
        public float fgWidth;
    }

    public partial class LoadingWnd : QFramework.UIPanel
    {
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as LoadingWndData ?? new LoadingWndData();
            // please add init code here
            mData.fgWidth = this.loadingfg.GetComponent<RectTransform>().sizeDelta.x;
            this.txtTips.text = "这是一条游戏Tips";
            this.txtPrg.text = "0%";
            this.loadingfg.fillAmount = 0;
            imgPoint.transform.localPosition = new Vector3(-545f, 0, 0);
        }

        public void SetProgress(float prg)
        {
            this.txtPrg.text = (int)(prg * 100) + "%";
            this.loadingfg.fillAmount = prg;

            float posX = prg * mData.fgWidth - 545;
            imgPoint.GetComponent<RectTransform>().anchoredPosition = new Vector2(posX, 0);
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }
    }
}
