//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYJ
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class LoginWnd
    {
        
        public const string NAME = "LoginWnd";
        
        [SerializeField()]
        public UnityEngine.UI.Button btnNotice;
        
        [SerializeField()]
        public UnityEngine.UI.Image logobg;
        
        [SerializeField()]
        public UnityEngine.UI.Image iptbg1;
        
        [SerializeField()]
        public UnityEngine.UI.Image iptbg2;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnEnter;
        
        private LoginWndData mPrivateData = null;
        
        public LoginWndData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new LoginWndData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            btnNotice = null;
            logobg = null;
            iptbg1 = null;
            iptbg2 = null;
            btnEnter = null;
            mData = null;
        }
    }
}
